googleapis/python-bigtable

- tests/system.py
Fixes #5 
- Skipping the tests which are failing with emulator.
> feat(bigtable): skip system tests failing with emulator

- google/cloud/bigtable/cluster.py
- google/cloud/bigtable/instance.py
- google/cloud/bigtable/table.py
> docs(bigtable): clean up

- samples/metricscaler/metricscaler.py
- samples/metricscaler/metricscaler_test.py
Transferring one commit that was left behind in python-docs-samples. Replaces #71 
---
#4237 BT metricscaler - Filter cpu query to get the metrics for the correct resources [(#4238)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4238)
* #4237 Added a filter to the cpu & storage queries to get the metrics for the correct resources
> docs(samples): filter cpu query to get metrics for the correct resources

- noxfile.py
Unbreaking the `docs-presubmit` build.
> chore: add docfx session to noxfile, normalize

- docs/instance-api.rst
- docs/row-filters.rst
- docs/table-api.rst
When we add new API, the line numbers for these docs in github can change. Switching to the client doc links so we don't have to update if line numbers change
> docs: switch links to client documentation

- docs/snippets_table.py
> tests: harden 'snippets_table.py' teardown against 429

- google/cloud/bigtable/client.py
- setup.py
- tests/unit/test_client.py
> feat: pass 'client_options' to base class ctor

- google/cloud/bigtable/table.py
An issue identified that in certain cases we weren't retrying `ServiceUnavailable`. According the stack trace, it seems to come from the initial call.
I am currently running a stress test against this change to see if the exception path is activated.
Fixes #115
> fix: retry if failure occurs on initial call in MutateRows

- google/cloud/bigtable/row.py
- tests/unit/test_row.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #127  🦕
> feat: add response status to DirectRow.commit()

- synth.py
- Remove those which no longer match.
- Apply '_GAPIC_LIBRARY_VERSION' tweak from PR #150.
Closes #155.
Closes #156.
> chore: clean up synth replacements

- google/cloud/bigtable/backup.py
- tests/unit/test_backup.py
Implementing Backup Level IAM methods.
> feat: Backup Level IAM

- google/cloud/bigtable/table.py
- tests/unit/test_table.py
Also, refactor implementation to avoid scribbling on the internals of the data client.
Closes #7
> feat: add 'timeout' arg to 'Table.mutate_rows'

- synth.py
See #150
Closes #162
Closes #163
> chore: tweak version lookup for non-admin client

- samples/metricscaler/metricscaler_test.py
- samples/metricscaler/requirements-test.txt
> tests: 'test_scale_bigtable', backoff when testing cluster node counts

- google/cloud/bigtable/backup.py
- noxfile.py
- tests/system.py
- tests/unit/test_backup.py
**The summary of proposed changes:**
- A new optional argument added to `Backup.restore` method, allowing users to specify Instance to restore the backup into, if different from the one the backup was created in.
**ToDo:**
- (edit: kolea2) update region to `LOCATION_ID` global variable.
> feat: backup restore to another Instance

- google/cloud/bigtable/row_filters.py
- tests/unit/test_row_filters.py
> feat: support filtering on incrementable values

- google/cloud/bigtable/client.py
- tests/unit/test_client.py
Fixes #181 
Added  `grpc.keepalive_time_ms` and `grpc.keepalive_timeout_ms` for an emulator as it used insecure channel.
Clients are gapic generated client so need to add in respective files:
1: https://github.com/googleapis/python-bigtable/blob/9b380a36df0652511639da7c128b80d39db1bc0c/google/cloud/bigtable_v2/gapic/transports/bigtable_grpc_transport.py#L67-L74
2 : https://github.com/googleapis/python-bigtable/blob/9b380a36df0652511639da7c128b80d39db1bc0c/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py#L71-L79
3: https://github.com/googleapis/python-bigtable/blob/9b380a36df0652511639da7c128b80d39db1bc0c/google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py#L71-L79
> feat: add keep alive timeout

- samples/instanceadmin/instanceadmin.py
In addition to showing the better practice (using the operation returned
from 'Instance.create' / 'Cluster.create'), this change also hardens
the sample against eventual-consistency issues.
Closes #353.
> doc(samples): use operation to ensure creation completed

- samples/instanceadmin/requirements.txt
- samples/instanceadmin/test_instanceadmin.py
Closes #353.
@kolea2 Note that this PR injects "repeatability" noise into the sample, which may be undesirable from the perspective of documentation.
> test(samples): add backoff to cluster creation sample

- samples/hello/README.md
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> chore(samples): Fixed a typo in the readme

- samples/hello/main.py
- samples/hello/main_test.py
Add region tags for 2 existing snippets
> docs(samples): add region tags

- samples/snippets/filters/filter_snippets_async.py
- samples/snippets/filters/filter_snippets_async_test.py
This adds missing samples for filters when using the async api
> doc: add samples for filtering using async apis

- samples/snippets/data_client/data_client_snippets_async.py
- fix missing `await` in async write_batch sample
- add exception handling to sample, giving info on each underlying failure
> chore(docs): improve write_batch async sample

- samples/quickstart/main_async.py
- samples/quickstart/main_async_test.py
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> chore(docs): add missing quickstart samples for asyncio

- samples/snippets/deletes/deletes_snippets.py
- samples/snippets/deletes/deletes_snippets_async.py
- samples/snippets/filters/filter_snippets.py
- samples/snippets/filters/filter_snippets_async.py
- samples/snippets/reads/read_snippets.py
This PR moves imports into each region tag (where missing), to make copy/pasting easier
internal bug: 372733665
> chore(docs): include imports in snippets
